### ISSUE TITLE
Error on Buttons

### ISSUE THREAD

**Issue by christerolsen** [christerolsen/project-exam-2-holidaze#70]
Warning: Button: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead. Error Component Stack
    at Button (index.jsx:5:19)
    at div (<anonymous>)
    at HomePage (<anonymous>)
    at RenderedRoute (hooks.tsx:658:26)
    at Outlet (components.tsx:333:26)
    at main (<anonymous>)
    at div (<anonymous>)
    at Layout (<anonymous>)
    at RenderedRoute (hooks.tsx:658:26)
    at Routes (components.tsx:504:3)
    at App (<anonymous>)
    at QueryClientProvider (QueryClientProvider.tsx:30:3)
    at Router (components.tsx:413:13)
    at BrowserRouter (index.tsx:783:3)

**Comment by christerolsen** [comment]
Fixed when creating VenueDetailsPage
